#include <drivers/keyboard/keymap.h>
#include <drivers/keyboard/layout.h>

keyboard_layout_t layout_us = {
    .name = "US",
    .keys_lower =
        {

            [NUM_1_KEY] = '1',
            [NUM_2_KEY] = '2',
            [NUM_3_KEY] = '3',
            [NUM_4_KEY] = '4',
            [NUM_5_KEY] = '5',
            [NUM_6_KEY] = '6',
            [NUM_7_KEY] = '7',
            [NUM_8_KEY] = '8',
            [NUM_9_KEY] = '9',
            [NUM_0_KEY] = '0',
            [MINUS_KEY] = '-',
            [EQUALS_KEY] = '=',
            [BACKSPACE_KEY] = '\b',
            [TAB_KEY] = '\t',
            [Q_KEY] = 'q',
            [W_KEY] = 'w',
            [E_KEY] = 'e',
            [R_KEY] = 'r',
            [T_KEY] = 't',
            [Y_KEY] = 'y',
            [U_KEY] = 'u',
            [I_KEY] = 'i',
            [O_KEY] = 'o',
            [P_KEY] = 'p',
            [LEFT_BRACKET_KEY] = '[',
            [RIGHT_BRACKET_KEY] = ']',
            [ENTER_KEY] = '\n',
            [A_KEY] = 'a',
            [S_KEY] = 's',
            [D_KEY] = 'd',
            [F_KEY] = 'f',
            [G_KEY] = 'g',
            [H_KEY] = 'h',
            [J_KEY] = 'j',
            [K_KEY] = 'k',
            [L_KEY] = 'l',
            [SEMICOLON_KEY] = ';',
            [SINGLE_QUOTE_KEY] = '\'',
            [BACKTICK_KEY] = '`',
            [BACKSLASH_KEY] = '\\',
            [Z_KEY] = 'z',
            [X_KEY] = 'x',
            [C_KEY] = 'c',
            [V_KEY] = 'v',
            [B_KEY] = 'b',
            [N_KEY] = 'n',
            [M_KEY] = 'm',
            [COMMA_KEY] = ',',
            [DOT_KEY] = '.',
            [SLASH_KEY] = '/',
        },
    .keys_upper =
        {
            [NUM_1_KEY] = '!',
            [NUM_2_KEY] = '@',
            [NUM_3_KEY] = '#',
            [NUM_4_KEY] = '$',
            [NUM_5_KEY] = '%',
            [NUM_6_KEY] = '^',
            [NUM_7_KEY] = '&',
            [NUM_8_KEY] = '*',
            [NUM_9_KEY] = '(',
            [NUM_0_KEY] = ')',
            [MINUS_KEY] = '_',
            [EQUALS_KEY] = '+',
            [BACKSPACE_KEY] = '\b',
            [TAB_KEY] = '\t',
            [Q_KEY] = 'Q',
            [W_KEY] = 'W',
            [E_KEY] = 'E',
            [R_KEY] = 'R',
            [T_KEY] = 'T',
            [Y_KEY] = 'Y',
            [U_KEY] = 'U',
            [I_KEY] = 'I',
            [O_KEY] = 'O',
            [P_KEY] = 'P',
            [LEFT_BRACKET_KEY] = '{',
            [RIGHT_BRACKET_KEY] = '}',
            [ENTER_KEY] = '\n',
            [A_KEY] = 'A',
            [S_KEY] = 'S',
            [D_KEY] = 'D',
            [F_KEY] = 'F',
            [G_KEY] = 'G',
            [H_KEY] = 'H',
            [J_KEY] = 'J',
            [K_KEY] = 'K',
            [L_KEY] = 'L',
            [SEMICOLON_KEY] = ':',
            [SINGLE_QUOTE_KEY] = '"',
            [BACKTICK_KEY] = '~',
            [BACKSLASH_KEY] = '|',
            [Z_KEY] = 'Z',
            [X_KEY] = 'X',
            [C_KEY] = 'C',
            [V_KEY] = 'V',
            [B_KEY] = 'B',
            [N_KEY] = 'N',
            [M_KEY] = 'M',
            [COMMA_KEY] = '<',
            [DOT_KEY] = '>',
            [SLASH_KEY] = '?',
            [SPACE_KEY] = ' ',
        },
};

keyboard_layout_t layout_fr;
